"""empty message

Revision ID: 4548a302f84c
Revises: 31dab25de1b0
Create Date: 2022-09-02 22:49:47.579762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4548a302f84c'
down_revision = '31dab25de1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studios', sa.Column('zip_code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studios', 'zip_code')
    # ### end Alembic commands ###
