"""empty message

Revision ID: 9c7f83e18aab
Revises: 4548a302f84c
Create Date: 2022-09-17 18:35:25.044941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7f83e18aab'
down_revision = '4548a302f84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('image_references2', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('image_references3', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'image_references3')
    op.drop_column('appointments', 'image_references2')
    # ### end Alembic commands ###
